# Generated by Django 2.1.1 on 2018-09-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_who', models.CharField(blank=True, max_length=50)),
                ('stichnr', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Needlesize',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projectideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Swatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('needlesize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Needlesize')),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nr_in_stash', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Manufacturer')),
                ('materials', models.ManyToManyField(to='strick.Material')),
                ('wash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Wash')),
                ('weight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Yarnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='yarn',
            name='yarnshops',
            field=models.ManyToManyField(blank=True, to='strick.Yarnshop'),
        ),
        migrations.AddField(
            model_name='swatch',
            name='yarn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Yarn'),
        ),
        migrations.AddField(
            model_name='projectideas',
            name='weight_id',
            field=models.ManyToManyField(blank=True, to='strick.Weight'),
        ),
        migrations.AddField(
            model_name='projectideas',
            name='yarn_id',
            field=models.ManyToManyField(blank=True, to='strick.Yarn'),
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='needlsize_id',
            field=models.ManyToManyField(to='strick.Needlesize'),
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='yarn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Yarn'),
        ),
    ]
