# Generated by Django 2.1.1 on 2018-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swatch',
            name='n_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_rows_washed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_stitches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_stitches_washed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='own_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yarn',
            name='superwash',
            field=models.BooleanField(default=False),
        ),
    ]
