# Generated by Django 2.1.1 on 2018-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='col_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
