# Generated by Django 2.1.1 on 2018-09-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, null=True)),
                ('col_nr', models.IntegerField(null=True)),
                ('own_it', models.BooleanField(default=False)),
                ('nr_in_stash', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('yarnshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Yarnshop')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectideas',
            name='weight_id',
        ),
        migrations.RemoveField(
            model_name='projectideas',
            name='yarn_id',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='col_nr',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='color',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='nr_in_stash',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='yarnshops',
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_rows_washed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_stitches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swatch',
            name='n_stitches_washed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='superwash',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Projectideas',
        ),
        migrations.AddField(
            model_name='color',
            name='yarntype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Yarn'),
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='color_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='strick.Color'),
            preserve_default=False,
        ),
    ]
