# Generated by Django 2.1.1 on 2018-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='id',
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
