# Generated by Django 2.1.1 on 2018-09-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0002_auto_20180915_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strick.Color')),
                ('weight_id', models.ManyToManyField(blank=True, to='strick.Weight')),
                ('yarn_id', models.ManyToManyField(blank=True, to='strick.Yarn')),
            ],
        ),
    ]
