# Generated by Django 2.0 on 2018-10-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0003_auto_20181008_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedobject',
            old_name='needlsize',
            new_name='needlesize',
        ),
        migrations.RenameField(
            model_name='finishedobject',
            old_name='for_who',
            new_name='recipient',
        ),
    ]
