# Generated by Django 2.1.1 on 2018-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0003_projectidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedobject',
            name='skeins_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
