# Generated by Django 2.1.1 on 2018-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0004_finishedobject_skeins_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedobject',
            old_name='needlsize_id',
            new_name='needlsize',
        ),
        migrations.RenameField(
            model_name='finishedobject',
            old_name='yarn_id',
            new_name='yarn',
        ),
        migrations.RenameField(
            model_name='projectidea',
            old_name='weight_id',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='projectidea',
            old_name='yarn_id',
            new_name='yarn',
        ),
        migrations.RenameField(
            model_name='swatch',
            old_name='needlesize_id',
            new_name='needlesize',
        ),
        migrations.RenameField(
            model_name='swatch',
            old_name='yarn_id',
            new_name='yarn',
        ),
        migrations.RemoveField(
            model_name='finishedobject',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='projectidea',
            name='color_id',
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='color',
            field=models.ManyToManyField(blank=True, to='strick.Color'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='color',
            field=models.ManyToManyField(blank=True, to='strick.Color'),
        ),
    ]
