# Generated by Django 2.0 on 2018-09-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0005_auto_20180917_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarn',
            old_name='manufacturer_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='yarn',
            old_name='wash_id',
            new_name='wash',
        ),
        migrations.RenameField(
            model_name='yarn',
            old_name='weight_id',
            new_name='weight',
        ),
    ]
