# Generated by Django 2.0 on 2018-09-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0006_auto_20180918_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='nr_in_stash',
            new_name='quantity',
        ),
    ]
