# Generated by Django 2.0 on 2018-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0007_auto_20180928_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='yardage_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='yardage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
