# Generated by Django 2.0 on 2018-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strick', '0008_auto_20181001_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='skeins_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
