# Generated by Django 2.0 on 2018-10-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('col_nr', models.IntegerField(null=True)),
                ('own_it', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_who', models.CharField(blank=True, max_length=50)),
                ('stichnr', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('skeins_used', models.IntegerField(blank=True, null=True)),
                ('color', models.ManyToManyField(blank=True, null=True, to='Backend.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Needlesize',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projectidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('yardage_needed', models.IntegerField(blank=True, null=True)),
                ('skeins_needed', models.IntegerField(blank=True, null=True)),
                ('color', models.ManyToManyField(blank=True, null=True, to='Backend.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Swatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('n_rows', models.IntegerField(blank=True, null=True)),
                ('n_stitches', models.IntegerField(blank=True, null=True)),
                ('n_rows_washed', models.IntegerField(blank=True, null=True)),
                ('n_stitches_washed', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('needlesize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Needlesize')),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('superwash', models.BooleanField(default=False)),
                ('yardage', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Manufacturer')),
                ('materials', models.ManyToManyField(to='Backend.Material')),
                ('wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Wash')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Yarnshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='swatch',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Yarn'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Weight'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='yarn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Yarn'),
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='needlsize',
            field=models.ManyToManyField(to='Backend.Needlesize'),
        ),
        migrations.AddField(
            model_name='finishedobject',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Yarn'),
        ),
        migrations.AddField(
            model_name='color',
            name='yarnshop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Yarnshop'),
        ),
        migrations.AddField(
            model_name='color',
            name='yarntype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Yarn'),
        ),
    ]
