# Generated by Django 2.0 on 2018-10-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedobject',
            name='color',
            field=models.ManyToManyField(blank=True, to='Backend.Color'),
        ),
        migrations.AlterField(
            model_name='finishedobject',
            name='yarn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.Yarn'),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='color',
            field=models.ManyToManyField(blank=True, to='Backend.Color'),
        ),
        migrations.AlterField(
            model_name='swatch',
            name='yarn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.Yarn'),
        ),
    ]
