# Generated by Django 2.1.2 on 2018-10-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181019_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedobject',
            name='projectidea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Projectidea'),
        ),
        migrations.AlterField(
            model_name='color',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
