# Generated by Django 2.1.2 on 2018-10-23 15:28

from django.db import migrations

def create_materials(apps, schema_editor):

    """create initial materials, can be modified"""
    Material = apps.get_model('Backend', 'Material')

    alpaca = Material(name='Alpaca')
    alpaca.save()
    cotton = Material(name='Cotton')
    cotton.save()
    merino = Material(name='Merino')
    merino.save()
    silk = Material(name='Silk')
    silk.save()
    yak = Material(name='Yak')
    yak.save()
    newwool = Material(name='New Wool')
    newwool.save()
    bamboo = Material(name='Bamboo')
    cashmere = Material(name='Cashmere')
    bamboo.save()
    cashmere.save()
    angora = Material(name='Angora')
    angora.save()
    hemp = Material(name='Hemp')
    hemp.save()
    linen = Material(name='Linen')
    linen.save()
    llama = Material(name='Llama')
    llama.save()
    microfiber = Material(name='Microfiber')
    microfiber.save()
    nylon = Material(name='Nylon')
    nylon.save()
    mohair = Material(name='Mohair')
    mohair.save()
    polyester = Material(name='Polyester')
    polyester.save()
    rayon = Material(name='Rayon')
    rayon.save()
    acrylic = Material(name='Acrylic')
    acrylic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20181023_0839'),
    ]

    operations = [migrations.RunPython(create_materials),
    ]
