# Generated by Django 2.1.2 on 2018-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20181023_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedobject',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
