# Generated by Django 2.1.2 on 2018-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20181029_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedobject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
